In [2]:
import pandas as pd

card = pd.read_csv('/content/card_data.csv')

In [3]:
card.head()

Card Name                   Annual_fee  \
0           하나 트래블로그 SKYPASS 신용카드  국내 4만8천원, 해외 4만8천원, 가족겸용 없음   
1                        DA카드의정석Ⅱ           국내 1만2천원, 해외 1만2천원   
2  삼성카드 & MILEAGE PLATINUM(스카이패스)           국내 4만7천원, 해외 4만9천원   
3          현대카드ZERO Edition3(할인형)   국내 1만5천원, 해외 1만5천원, 가족 5천원   
4                   삼성카드 taptap O               국내 1만원, 해외 1만원   

         Base Record                                      Category_List  
0               조건없음                                         ['항공마일리지']  
1  직전 1개월 합계 30만원 이상  ['쇼핑', '레저', '카페/베이커리', '편의점', '대형마트', '의료', '...  
2               조건없음  ['쇼핑', '주유', '카페/베이커리', '편의점', '대중교통', '간편결제',...  
3               조건없음  ['대중교통', '간편결제', '편의점', '통신', '카페/베이커리', '대형마트...  
4  직전 1개월 합계 30만원 이상  ['포인트/캐시백', '카페/베이커리', '쇼핑', '통신', '대중교통', '영화...

### 1. Feature Vectorization

In [36]:
# 리스트 데이터를 문자열로 변환
card['Category_String'] = card['Category_List'].apply(lambda x: x.split(',')).apply(lambda x: " ".join(x))
card['Category_String'].head()

0                                           ['항공마일리지']
1    ['쇼핑'  '레저'  '카페/베이커리'  '편의점'  '대형마트'  '의료'  '...
2    ['쇼핑'  '주유'  '카페/베이커리'  '편의점'  '대중교통'  '간편결제' ...
3    ['대중교통'  '간편결제'  '편의점'  '통신'  '카페/베이커리'  '대형마트...
4    ['포인트/캐시백'  '카페/베이커리'  '쇼핑'  '통신'  '대중교통'  '영화...
Name: Category_String, dtype: object

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

# 리스트 데이터를 문자열로 변환
# card['Category_String'] = card['Category_List'].apply(lambda x: " ".join(x))

# CountVectorizer 설정
vectorizer = CountVectorizer()

# 문자열 데이터를 벡터화
X = vectorizer.fit_transform(card['Category_String'])

# 결과 출력
print("Feature names:", vectorizer.get_feature_names_out())
print("Vectorized data:\n", X.toarray())

Feature names: ['간편결제' '관리비' '교육' '납부' '대중교통' '대형마트' '레저' '문화' '반려동물' '베이커리' '뷰티' '쇼핑'
 '영화' '외식' '육아' '의료' '주유' '카페' '캐시백' '통신' '편의점' '포인트' '하이패스' '항공마일리지' '혜택']
Vectorized data:
 [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
card.head()

Card Name                   Annual_fee  \
0           하나 트래블로그 SKYPASS 신용카드  국내 4만8천원, 해외 4만8천원, 가족겸용 없음   
1                        DA카드의정석Ⅱ           국내 1만2천원, 해외 1만2천원   
2  삼성카드 & MILEAGE PLATINUM(스카이패스)           국내 4만7천원, 해외 4만9천원   
3          현대카드ZERO Edition3(할인형)   국내 1만5천원, 해외 1만5천원, 가족 5천원   
4                   삼성카드 taptap O               국내 1만원, 해외 1만원   

         Base Record                                      Category_List  \
0               조건없음                                         ['항공마일리지']   
1  직전 1개월 합계 30만원 이상  ['쇼핑', '레저', '카페/베이커리', '편의점', '대형마트', '의료', '...   
2               조건없음  ['쇼핑', '주유', '카페/베이커리', '편의점', '대중교통', '간편결제',...   
3               조건없음  ['대중교통', '간편결제', '편의점', '통신', '카페/베이커리', '대형마트...   
4  직전 1개월 합계 30만원 이상  ['포인트/캐시백', '카페/베이커리', '쇼핑', '통신', '대중교통', '영화...   

                                     Category_String  
0                                         ['항공마일리지']  
1  ['쇼핑'  '레저'  '카페/베이커리'  '편의점'  '대형마트'  '의료'  '...  
2  ['쇼핑'  '주유'  '카페/베이커리'  '편의점'  '대중교통'  '간편결제' ...  
3  ['대중교통'  '간편결제'  '편의점'  '통신'  '카페/베이커리'  '대형마트...  
4  ['포인트/캐시백'  '카페/베이커리'  '쇼핑'  '통신'  '대중교통'  '영화...

In [39]:
count_vect = CountVectorizer(ngram_range=(1,2))
category_matrix = count_vect.fit_transform(card['Category_String'])
category_matrix

<166x265 sparse matrix of type '<class 'numpy.int64'>'
	with 2004 stored elements in Compressed Sparse Row format>

In [40]:
category_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### 2. 코사인 유사도

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

cate_sim = cosine_similarity(category_matrix, category_matrix)
cate_sim.shape

(166, 166)

In [42]:
cate_sim[0, :20]

array([1.        , 0.        , 0.16439899, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [43]:
card_sim_sorted_index = cate_sim.argsort()[:, ::-1]
card_sim_sorted_index[0:10]

array([[  0,  25, 125, ..., 100,  99,  82],
       [  1,  90,  12, ..., 108, 116,   0],
       [  2,  40,  51, ...,  19, 116,  82],
       ...,
       [  7,  62, 149, ..., 116, 118,   0],
       [148,   8, 114, ..., 110, 112,   0],
       [  9,  81,  45, ..., 119, 120,   0]])

In [44]:
def find_sim_card(df, sorted_index, card_name, top_n =4):
  # 1. card name 찾기
  card_name = card[card['Card Name']==card_name]

  # 2. 찾고자 하는 카드의 인덱스 찾기
  card_index = card_name.index.values
  similar_indexes = sorted_index[card_index, :top_n]

  similar_indexes = similar_indexes.reshape(-1) # 1차원 배열로 만들어 주기

  return df.iloc[similar_indexes]

In [45]:
similar_card_df = find_sim_card(card, card_sim_sorted_index,"KB국민 그린카드(서울형)")

In [46]:
similar_card_df

Card Name                 Annual_fee        Base Record  \
164       KB국민 그린카드(서울형)           국내전용 없음, 해외겸용 없음  직전 1개월 합계 20만원 이상   
53        KB국민 그린카드(전국형)           국내전용 없음, 해외겸용 없음  직전 1개월 합계 20만원 이상   
139        현대백화점 해피포인트카드  국내전용 없음, 해외겸용 없음, 가족겸용 없음               조건없음   
38   카드의정석 Dear, Shopper           국내 15만원, 해외 15만원  직전 1개월 합계 50만원 이상   

                         Category_List                    Category_String  
164  ['포인트/캐시백', '대중교통', '쇼핑', '대형마트']  ['포인트/캐시백'  '대중교통'  '쇼핑'  '대형마트']  
53   ['포인트/캐시백', '대중교통', '쇼핑', '대형마트']  ['포인트/캐시백'  '대중교통'  '쇼핑'  '대형마트']  
139                  ['포인트/캐시백', '쇼핑']                  ['포인트/캐시백'  '쇼핑']  
38                   ['포인트/캐시백', '쇼핑']                  ['포인트/캐시백'  '쇼핑']

In [15]:
card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Card Name        166 non-null    object
 1   Annual_fee       166 non-null    object
 2   Base Record      166 non-null    object
 3   Category_List    166 non-null    object
 4   Category_String  166 non-null    object
dtypes: object(5)
memory usage: 6.6+ KB


In [17]:
card.drop_duplicates('Card Name')

Card Name                   Annual_fee  \
0             하나 트래블로그 SKYPASS 신용카드  국내 4만8천원, 해외 4만8천원, 가족겸용 없음   
1                          DA카드의정석Ⅱ           국내 1만2천원, 해외 1만2천원   
2    삼성카드 & MILEAGE PLATINUM(스카이패스)           국내 4만7천원, 해외 4만9천원   
3            현대카드ZERO Edition3(할인형)   국내 1만5천원, 해외 1만5천원, 가족 5천원   
4                     삼성카드 taptap O               국내 1만원, 해외 1만원   
..                              ...                          ...   
161              LOCA PLATINUM(할인형)    국내 10만원, 해외 10만원, 가족겸용 없음   
162                 I-MILEAGE(아시아나)           국내 4만1천원, 해외 4만2천원   
163           The CJ-현대카드M Edition2             국내 1만5천원, 해외 2만원   
164                  KB국민 그린카드(서울형)             국내전용 없음, 해외겸용 없음   
165         KB국민 Green Wave 1.5℃ 카드           국내 1만5천원, 해외 1만5천원   

           Base Record                                      Category_List  \
0                 조건없음                                         ['항공마일리지']   
1    직전 1개월 합계 30만원 이상  ['쇼핑', '레저', '카페/베이커리', '편의점', '대형마트', '의료', '...   
2                 조건없음  ['쇼핑', '주유', '카페/베이커리', '편의점', '대중교통', '간편결제',...   
3                 조건없음  ['대중교통', '간편결제', '편의점', '통신', '카페/베이커리', '대형마트...   
4    직전 1개월 합계 30만원 이상  ['포인트/캐시백', '카페/베이커리', '쇼핑', '통신', '대중교통', '영화...   
..                 ...                                                ...   
161               조건없음  ['카페/베이커리', '쇼핑', '뷰티', '대형마트', '편의점', '주유', '...   
162  직전 1개월 합계 50만원 이상                              ['항공마일리지', '카페/베이커리']   
163               조건없음           ['쇼핑', '영화', '외식', '카페/베이커리', '포인트/캐시백']   
164  직전 1개월 합계 20만원 이상                  ['포인트/캐시백', '대중교통', '쇼핑', '대형마트']   
165  직전 1개월 합계 40만원 이상              ['포인트/캐시백', '주유', '대중교통', '문화', '쇼핑']   

                                       Category_String  
0                                           ['항공마일리지']  
1    ['쇼핑', '레저', '카페/베이커리', '편의점', '대형마트', '의료', '...  
2    ['쇼핑', '주유', '카페/베이커리', '편의점', '대중교통', '간편결제',...  
3    ['대중교통', '간편결제', '편의점', '통신', '카페/베이커리', '대형마트...  
4    ['포인트/캐시백', '카페/베이커리', '쇼핑', '통신', '대중교통', '영화...  
..                                                 ...  
161  ['카페/베이커리', '쇼핑', '뷰티', '대형마트', '편의점', '주유', '...  
162                              ['항공마일리지', '카페/베이커리']  
163           ['쇼핑', '영화', '외식', '카페/베이커리', '포인트/캐시백']  
164                  ['포인트/캐시백', '대중교통', '쇼핑', '대형마트']  
165              ['포인트/캐시백', '주유', '대중교통', '문화', '쇼핑']  

[166 rows x 5 columns]

In [18]:
card[card['Card Name'] == '신한카드 국민행복']

Card Name        Annual_fee        Base Record  \
33  신한카드 국민행복  국내전용 없음, 해외겸용 없음  직전 1개월 합계 30만원 이상   

                     Category_List                 Category_String  
33  ['의료', '쇼핑', '교육', '외식', '문화']  ['의료', '쇼핑', '교육', '외식', '문화']